### ISSUE TITLE
Getting System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by moosetwin0** [Rainson12/FactorioSaveGameEnableAchievements#2]
Here's an image of the issue:
![image](https://github.com/user-attachments/assets/c297c449-2dfa-47ac-8795-99144f2b2ef5)

This causes the program to create a folder that is identical to the extracted save zip file.

Things I have tried:
- Putting the save file path in quotes
- Running the program as administrator
- Moving the save file to the same folder as the program
- Replacing all '\\'s with '/'s

**Comment by moosetwin0** [comment]
My game version is 2.0.23, with Space Age.

**Comment by louanfontenele** [comment]
same for me

**Comment by louanfontenele** [comment]
@Rainson12

**Comment by louanfontenele** [comment]
> Here's an image of the issue: ![image](https://private-user-images.githubusercontent.com/82544732/395778101-c297c449-2dfa-47ac-8795-99144f2b2ef5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMTQ2OTksIm5iZiI6MTczNTIxNDM5OSwicGF0aCI6Ii84MjU0NDczMi8zOTU3NzgxMDEtYzI5N2M0NDktMmRmYS00N2FjLTg3OTUtOTkxNDRmMmIyZWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDExNTk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNWE4ZTI0MGM2ZjM4MTBhZTIyYzFkNTE4NDY5Mjc2NDgwYmI0ZWNhMTA5ZWUxYTFiZjI2YjlmNWU0NDk0YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gFstnSDyw2JjfbyXE0fHRwvvlijYYmbe4X74Q8mJb1s)
> 
> This causes the program to create a folder that is identical to the extracted save zip file.
> 
> Things I have tried:
> 
> * Putting the save file path in quotes
> * Running the program as administrator
> * Moving the save file to the same folder as the program
> * Replacing all '\'s with '/'s


A fix: [FactorioSaveGameEnableAchievements.zip](https://github.com/user-attachments/files/18252575/FactorioSaveGameEnableAchievements.zip)

I've created a pull request to fix this problem:
https://github.com/Rainson12/FactorioSaveGameEnableAchievements/pull/3

**Comment by Rainson12** [comment]
fixed by @louanfontenele - Thanks!
